replicas: 1
version: '0.1'

eureka:
  name: eureka-server-qa
  image: eureka-server
  tag: '0.1'
  fullnameOverride: ""
  nameOverride: ""
  replicas: 1
  ports:
    name: Port 1
    port: 8761
    protocol: TCP
gateway:
  name: api-gateway-qa
  image: api-gateway
  tag: '0.1'
  fullnameOverride: ""
  nameOverride: ""
  replicas: 1
  ports:
    name: Port 2
    port: 8762
jobs:
  name: jobs-service-qa
  image: jobs-service
  tag: '0.1'
  fullnameOverride: ""
  nameOverride: ""
  replicas: 1
  ports:
    name: Port 3
    port: 8200
    protocol: TCP
jobsuser:
  name: jobs-user-service-qa
  image: jobs-user-service
  tag: '0.1'
  fullnameOverride: ""
  nameOverride: ""
  replicas: 1
  ports:
    name: Port 4
    port: 8300
    protocol: TCP
account: 
  name: account-service-qa
  image: account-service
  tag: '0.1'
  fullnameOverride: ""
  nameOverride: ""
  replicas: 1
  ports:
    name: Port 5
    port: 8100
    protocol: TCP
cv:
  name: cv-service-qa
  image: cv-service
  tag: '0.1'
  fullnameOverride: ""
  nameOverride: ""
  replicas: 1
  ports:
    name: Port 6
    port: 8400
    protocol: TCP

# Default values for test.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
