apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.gateway.name }}
spec:
  type: NodePort
  ports:
  - port: 8762
    targetPort: 8762
    protocol: TCP
    name: http2
    nodePort: 31001
  selector:
    app: {{ .Values.gateway.name }}