apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.eureka.name }}
spec:
  type: NodePort
  ports:
  - port: 8761
    targetPort: 8761
    protocol: TCP
    name: http
    nodePort: 31000
  selector:
    app: {{ .Values.eureka.name }}